language: ruby
cache: bundler
sudo: false
before_install: 
  - bundle install
dist: trusty
matrix:
  fast_finish: true
  include:
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
script: FOG_MOCK=true rake test
